name: naia-os
description: Naia - Personal AI OS with virtual avatar
base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: rpm-ostree
    install:
      # Flatpak runtime (needed for flatpak install in first-boot service)
      - flatpak
      # Korean input
      - fcitx5
      - fcitx5-hangul
      - fcitx5-configtool
      - fcitx5-gtk
      - fcitx5-qt
      - google-noto-sans-cjk-kr-fonts
      # Utilities
      - jq
      - sqlite
      - podman

  - type: script
    scripts:
      - install-naia-shell.sh
      - branding.sh

  - type: files
    files:
      - source: usr
        destination: /usr

  - type: default-flatpaks
    configurations:
      - scope: system
        repo:
          url: https://flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: Flathub
        install:
          - com.google.Chrome
          - com.discordapp.Discord

  - type: signing
