name: naia-os
description: Naia OS - Personal AI OS with virtual avatar
base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: rpm-ostree
    install:
      - nodejs
      - npm
      # Tauri 2 runtime dependencies
      - webkit2gtk4.1
      - openssl-libs
      - libappindicator-gtk3
      - librsvg2
      - libxdo
      # Korean input
      - fcitx5
      - fcitx5-hangul
      - fcitx5-configtool
      - fcitx5-gtk
      - fcitx5-qt
      - google-noto-sans-cjk-kr-fonts
      # Utilities
      - jq
      - sqlite
      - podman

  - type: script
    scripts:
      - install-pnpm.sh
      - install-naia-shell.sh
      - setup-openclaw.sh
      - branding.sh

  - type: files
    files:
      - source: usr
        destination: /usr

  - type: default-flatpaks
    configurations:
      - scope: system
        repo:
          url: https://flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: Flathub
        install:
          - com.google.Chrome
          - com.discordapp.Discord

  - type: signing
