name: cafelua-os
description: Cafelua OS - Personal AI OS with virtual avatar
base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: rpm-ostree
    install:
      - nodejs
      - npm
      # Tauri 2 build dependencies
      - webkit2gtk4.1-devel
      - openssl-devel
      - libappindicator-gtk3-devel
      - librsvg2-devel
      - libxdo-devel
      - gcc
      - gcc-c++
      - make
      - pkg-config
      # Korean input
      - fcitx5
      - fcitx5-hangul
      - fcitx5-configtool
      - fcitx5-gtk
      - fcitx5-qt
      - google-noto-sans-cjk-kr-fonts
      # Utilities
      - sqlite
      - podman

  - type: script
    scripts:
      - install-pnpm.sh
      - branding.sh

  - type: files
    files:
      - source: usr
        destination: /usr

  - type: signing
